#!/bin/bash

# Verificar si docker esta instalado
if ! command -v docker &> /dev/null
then
    echo "Error: Docker no está instalado."
    exit 1
fi

# Construimos imagen de docker
docker build -t token:latest .

if [ $? -eq 0 ]; then
    echo "Imagen de Docker construida correctamente: token:latest"
else
    echo "Error al construir la imagen de Docker."
    exit 1
fi
